{
  "formatVersion": "1.1",
  "component": {
    "url": "../../shared/0.2.0/shared-0.2.0.module",
    "group": "com.hdc.adsmultiplatform",
    "module": "shared",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "shared.aar",
          "url": "shared-android-0.2.0.aar",
          "size": 5414828,
          "sha512": "172508809dc79a3c735a6e2823d732fdf618d27635df885ba193fff66b8071d70fd4698fe2d1b691be61b787b9601b3962d5e9feab85a3330596dd34fde6026f",
          "sha256": "ed952a5dd775563f7d9e6ef054fdf470442fb5e930f19c9686d373c715866ee6",
          "sha1": "9dac667364ecc03a653e0e14de6198715bb7d36a",
          "md5": "4f45af6a58e184fac6bdea05a4a6361c"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "audience-network-sdk",
          "version": {
            "requires": "6.22.0"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "facebook",
          "version": {
            "requires": "6.22.0.0"
          }
        },
        {
          "group": "com.tarifchakder",
          "module": "ktoast",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "shared.aar",
          "url": "shared-android-0.2.0.aar",
          "size": 5414828,
          "sha512": "172508809dc79a3c735a6e2823d732fdf618d27635df885ba193fff66b8071d70fd4698fe2d1b691be61b787b9601b3962d5e9feab85a3330596dd34fde6026f",
          "sha256": "ed952a5dd775563f7d9e6ef054fdf470442fb5e930f19c9686d373c715866ee6",
          "sha1": "9dac667364ecc03a653e0e14de6198715bb7d36a",
          "md5": "4f45af6a58e184fac6bdea05a4a6361c"
        }
      ]
    }
  ]
}
