{
  "formatVersion": "1.1",
  "component": {
    "url": "../../shared/0.1.0/shared-0.1.0.module",
    "group": "com.hdc.adsmultiplatform",
    "module": "shared",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "shared.aar",
          "url": "shared-android-0.1.0.aar",
          "size": 5349886,
          "sha512": "67e7abe79e465fc6f07f19a33d79a348a269676821d6383aed421011406c7c27f665919174f14065e17a2d83c49f4eb133394f1af1a52406eb8d532b84c6763f",
          "sha256": "a9a932e1a42924249f3413e22b993dc555f53836084f08bf00455557551d2904",
          "sha1": "eef11d40355d5b69752cefd3e232960710c2daed",
          "md5": "292c5474cd3f0a3b7236318219a34f81"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.9.0"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "audience-network-sdk",
          "version": {
            "requires": "6.22.0"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "facebook",
          "version": {
            "requires": "6.22.0.0"
          }
        },
        {
          "group": "com.tarifchakder",
          "module": "ktoast",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "shared.aar",
          "url": "shared-android-0.1.0.aar",
          "size": 5349886,
          "sha512": "67e7abe79e465fc6f07f19a33d79a348a269676821d6383aed421011406c7c27f665919174f14065e17a2d83c49f4eb133394f1af1a52406eb8d532b84c6763f",
          "sha256": "a9a932e1a42924249f3413e22b993dc555f53836084f08bf00455557551d2904",
          "sha1": "eef11d40355d5b69752cefd3e232960710c2daed",
          "md5": "292c5474cd3f0a3b7236318219a34f81"
        }
      ]
    }
  ]
}
